### ISSUE TITLE
Upgrade to Node 20

### ISSUE THREAD

**Issue by philipp-eisen** [depot/build-push-action#27]
Hey!

I'm getting deprecation warnings like the one below in our workflow summaries. 

<img width="1669" alt="Screenshot 2024-01-25 at 11 48 47" src="https://github.com/depot/build-push-action/assets/8607233/909180e4-a9cc-44c6-887f-1a5b4a150b5e">

https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

**Comment by kylegalbraith** [comment]
This should be fixed now as well ✅
